- hosts: all
  vars:
    srcdir: "{{ zuul.project.src_dir }}"
  tasks:
    - name: Run 'unit test'
      command: >
        ./gradlew
        --continue
        clean
        test
      args:
        chdir: "{{ srcdir }}"
